---
title: "Exercise crosstalk map"
subtitle:  "linked brushing with DT & leaflet"
output: html_document
---

## Library Packages

```{r}
library(tidyverse)
library(leaflet)
library(DT)
library(crosstalk)
```

## Load Data

```{r}
map <- read_csv("data/mockaroo_latlon.csv")

map
```


## Plot Map  via Leaflet

```{r}
leaf_map <- map %>% 
  leaflet(width = "100%") %>% 
  addTiles() %>% 
  addMarkers(lat = ~Latitude, 
             lng = ~Longitude, 
             popup = ~Company)

leaf_map
```

## DT data table

```{r}
mapdata_table <- datatable(map, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))

mapdata_table
```


## Crosstalk

make shared data structure

```{r}
shared_map <- SharedData$new(map)
```


### Rebuild widgets with shared data

Map

```{r}
shared_leaf_map <- shared_map %>% 
  leaflet(width = "100%") %>% 
  addTiles() %>% 
  addMarkers(lat = ~Latitude, 
             lng = ~Longitude, 
             popup = ~Company)

shared_leaf_map
```

data table

```{r}
shared_mapdata_table <- datatable(shared_map, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))

shared_mapdata_table
```


## bscols

```{r}
bscols(shared_leaf_map, shared_mapdata_table)
```

